language: java

jdk:
- openjdk8

before_install:
  - wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.0/apache-maven-3.6.0-bin.tar.gz
  - tar xzvf apache-maven-3.6.0-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.0/bin:$PATH
  - mvn -v

script:
- mvn test verify --batch-mode
