language: java

jdk:
- openjdk11

before_install:
  - wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.2/apache-maven-3.8.2-bin.tar.gz
  - tar xzvf apache-maven-3.8.2-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.8.2/bin:$PATH
  - mvn -v

script:
- mvn test verify --batch-mode

cache:
  directories:
  - $HOME/.m2
