//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 06:02:18 PM BRST 
//

package br.com.caelum.stella.nfe.modelo;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public Adi createAdi() {
        return new Adi();
    }

    public Arma createArma() {
        return new Arma();
    }

    public Avulsa createAvulsa() {
        return new Avulsa();
    }

    public CanonicalizationMethod createCanonicalizationMethod() {
        return new CanonicalizationMethod();
    }

    public CIDE createCIDE() {
        return new CIDE();
    }

    public Cobr createCobr() {
        return new Cobr();
    }

    public COFINS createCOFINS() {
        return new COFINS();
    }

    public COFINSAliq createCOFINSAliq() {
        return new COFINSAliq();
    }

    public COFINSNT createCOFINSNT() {
        return new COFINSNT();
    }

    public COFINSOutr createCOFINSOutr() {
        return new COFINSOutr();
    }

    public COFINSQtde createCOFINSQtde() {
        return new COFINSQtde();
    }

    public COFINSST createCOFINSST() {
        return new COFINSST();
    }

    public Comb createComb() {
        return new Comb();
    }

    public Compra createCompra() {
        return new Compra();
    }

    public Dest createDest() {
        return new Dest();
    }

    public Det createDet() {
        return new Det();
    }

    public DI createDI() {
        return new DI();
    }

    public DigestMethod createDigestMethod() {
        return new DigestMethod();
    }

    public Dup createDup() {
        return new Dup();
    }

    public Emit createEmit() {
        return new Emit();
    }

    public Exporta createExporta() {
        return new Exporta();
    }

    public Fat createFat() {
        return new Fat();
    }

    public ICMS createICMS() {
        return new ICMS();
    }

    public ICMS00 createICMS00() {
        return new ICMS00();
    }

    public ICMS10 createICMS10() {
        return new ICMS10();
    }

    public ICMS20 createICMS20() {
        return new ICMS20();
    }

    public ICMS30 createICMS30() {
        return new ICMS30();
    }

    public ICMS40 createICMS40() {
        return new ICMS40();
    }

    public ICMS51 createICMS51() {
        return new ICMS51();
    }

    public ICMS60 createICMS60() {
        return new ICMS60();
    }

    public ICMS70 createICMS70() {
        return new ICMS70();
    }

    public ICMS90 createICMS90() {
        return new ICMS90();
    }

    public ICMSComb createICMSComb() {
        return new ICMSComb();
    }

    public ICMSCons createICMSCons() {
        return new ICMSCons();
    }

    public ICMSInter createICMSInter() {
        return new ICMSInter();
    }

    public ICMSTot createICMSTot() {
        return new ICMSTot();
    }

    public Ide createIde() {
        return new Ide();
    }

    public II createII() {
        return new II();
    }

    public Imposto createImposto() {
        return new Imposto();
    }

    public InfAdic createInfAdic() {
        return new InfAdic();
    }

    public InfNFe createInfNFe() {
        return new InfNFe();
    }

    public InfProt createInfProt() {
        return new InfProt();
    }

    public InfRec createInfRec() {
        return new InfRec();
    }

    public IPI createIPI() {
        return new IPI();
    }

    public IPINT createIPINT() {
        return new IPINT();
    }

    public IPITrib createIPITrib() {
        return new IPITrib();
    }

    public ISSQN createISSQN() {
        return new ISSQN();
    }

    public ISSQNtot createISSQNtot() {
        return new ISSQNtot();
    }

    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    public Lacres createLacres() {
        return new Lacres();
    }

    public Med createMed() {
        return new Med();
    }

    public NFref createNFref() {
        return new NFref();
    }

    public ObsCont createObsCont() {
        return new ObsCont();
    }

    public ObsFisco createObsFisco() {
        return new ObsFisco();
    }

    public PIS createPIS() {
        return new PIS();
    }

    public PISAliq createPISAliq() {
        return new PISAliq();
    }

    public PISNT createPISNT() {
        return new PISNT();
    }

    public PISOutr createPISOutr() {
        return new PISOutr();
    }

    public PISQtde createPISQtde() {
        return new PISQtde();
    }

    public PISST createPISST() {
        return new PISST();
    }

    public ProcRef createProcRef() {
        return new ProcRef();
    }

    public Prod createProd() {
        return new Prod();
    }

    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    public RefNF createRefNF() {
        return new RefNF();
    }

    public RetTransp createRetTransp() {
        return new RetTransp();
    }

    public RetTrib createRetTrib() {
        return new RetTrib();
    }

    public SignatureMethod createSignatureMethod() {
        return new SignatureMethod();
    }

    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    public SignatureValueType createSignatureValueType() {
        return new SignatureValueType();
    }

    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    public TConsReciNFe createTConsReciNFe() {
        return new TConsReciNFe();
    }

    public TEndereco createTEndereco() {
        return new TEndereco();
    }

    public TEnviNFe createTEnviNFe() {
        return new TEnviNFe();
    }

    public TLocal createTLocal() {
        return new TLocal();
    }

    public TNFe createTNFe() {
        return new TNFe();
    }

    public TNfeProc createTNfeProc() {
        return new TNfeProc();
    }

    public Total createTotal() {
        return new Total();
    }

    public TProtNFe createTProtNFe() {
        return new TProtNFe();
    }

    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    public TransformType createTransformType() {
        return new TransformType();
    }

    public Transp createTransp() {
        return new Transp();
    }

    public Transporta createTransporta() {
        return new Transporta();
    }

    public TRetConsReciNFe createTRetConsReciNFe() {
        return new TRetConsReciNFe();
    }

    public TRetEnviNFe createTRetEnviNFe() {
        return new TRetEnviNFe();
    }

    public TVeiculo createTVeiculo() {
        return new TVeiculo();
    }

    public VeicProd createVeicProd() {
        return new VeicProd();
    }

    public Vol createVol() {
        return new Vol();
    }

    public X509DataType createX509DataType() {
        return new X509DataType();
    }
}
