//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.23 at 03:29:23 PM BRT 
//


package br.com.caelum.stella.nfe.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAtuCadEmiDFe", namespace = "http://www.portalfiscal.inf.br/nfe", propOrder = {
    "infAtuCadEmiDFe",
    "signature"
})
public class TAtuCadEmiDFe {

    @XmlElement(namespace = "http://www.portalfiscal.inf.br/nfe", required = true)
    protected InfAtuCadEmiDFe infAtuCadEmiDFe;
    @XmlElement(name = "Signature", required = true)
    protected SignatureType signature;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String versao;

    
    public InfAtuCadEmiDFe getInfAtuCadEmiDFe() {
        return infAtuCadEmiDFe;
    }

    
    public void setInfAtuCadEmiDFe(InfAtuCadEmiDFe value) {
        this.infAtuCadEmiDFe = value;
    }

    
    public SignatureType getSignature() {
        return signature;
    }

    
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    
    public String getVersao() {
        return versao;
    }

    
    public void setVersao(String value) {
        this.versao = value;
    }

}
