//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 06:02:18 PM BRST 
//

package br.com.caelum.stella.nfe.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import net.vidageek.fluid.annotations.FluidDataType;
import net.vidageek.fluid.annotations.FluidName;
import br.com.caelum.stella.tinytype.CNPJ;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLocal", propOrder = { "cnpj", "xLgr", "nro", "xCpl", "xBairro", "cMun", "xMun", "uf" })
@FluidName("DadosDoLocal")
public class TLocal {

    @XmlElement(name = "CNPJ", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("CNPJ")
    @FluidDataType(CNPJ.class)
    protected String cnpj;

    @XmlElement(required = true)
    @FluidName("logradouro")
    protected String xLgr;

    @XmlElement(required = true)
    @FluidName("numero")
    protected String nro;

    @FluidName("complemento")
    protected String xCpl;

    @XmlElement(required = true)
    @FluidName("bairro")
    protected String xBairro;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("codigoDoMunicipio")
    protected String cMun;

    @XmlElement(required = true)
    @FluidName("nomeDoMunicipio")
    protected String xMun;

    @XmlElement(name = "UF", required = true)
    @FluidName("UF")
    @FluidDataType(UF.class)
    protected UF uf;

    public String getCNPJ() {
        return cnpj;
    }

    public void setCNPJ(final String value) {
        cnpj = value;
    }

    public String getXLgr() {
        return xLgr;
    }

    public void setXLgr(final String value) {
        xLgr = value;
    }

    public String getNro() {
        return nro;
    }

    public void setNro(final String value) {
        nro = value;
    }

    public String getXCpl() {
        return xCpl;
    }

    public void setXCpl(final String value) {
        xCpl = value;
    }

    public String getXBairro() {
        return xBairro;
    }

    public void setXBairro(final String value) {
        xBairro = value;
    }

    public String getCMun() {
        return cMun;
    }

    public void setCMun(final String value) {
        cMun = value;
    }

    public String getXMun() {
        return xMun;
    }

    public void setXMun(final String value) {
        xMun = value;
    }

    public UF getUF() {
        return uf;
    }

    public void setUF(final UF value) {
        uf = value;
    }

}
