//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 06:02:18 PM BRST 
//

package br.com.caelum.stella.nfe.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import net.vidageek.fluid.annotations.FluidName;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNFe", propOrder = { "infNFe", "signature" })
@FluidName("NFE")
public class TNFe {

    @XmlElement(required = true)
    @FluidName("informacoesDaNFE")
    protected InfNFe infNFe;

    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    @FluidName("signature")
    protected SignatureType signature;

    public InfNFe getInfNFe() {
        return infNFe;
    }

    public void setInfNFe(final InfNFe value) {
        infNFe = value;
    }

    public SignatureType getSignature() {
        return signature;
    }

    public void setSignature(final SignatureType value) {
        signature = value;
    }

}
