//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 06:02:18 PM BRST 
//


package br.com.caelum.stella.nfe.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TProtNFe", propOrder = {
    "infProt",
    "signature"
})
public class TProtNFe {

    @XmlElement(required = true)
    protected TProtNFe.InfProt infProt;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected SignatureType signature;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String versao;

    
    public TProtNFe.InfProt getInfProt() {
        return infProt;
    }

    
    public void setInfProt(TProtNFe.InfProt value) {
        this.infProt = value;
    }

    
    public SignatureType getSignature() {
        return signature;
    }

    
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    
    public String getVersao() {
        return versao;
    }

    
    public void setVersao(String value) {
        this.versao = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tpAmb",
        "verAplic",
        "chNFe",
        "dhRecbto",
        "nProt",
        "digVal",
        "cStat",
        "xMotivo"
    })
    public static class InfProt {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String tpAmb;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String verAplic;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String chNFe;
        @XmlElement(required = true)
        protected XMLGregorianCalendar dhRecbto;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String nProt;
        protected byte[] digVal;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String cStat;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String xMotivo;
        @XmlAttribute(name = "Id")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        
        public String getTpAmb() {
            return tpAmb;
        }

        
        public void setTpAmb(String value) {
            this.tpAmb = value;
        }

        
        public String getVerAplic() {
            return verAplic;
        }

        
        public void setVerAplic(String value) {
            this.verAplic = value;
        }

        
        public String getChNFe() {
            return chNFe;
        }

        
        public void setChNFe(String value) {
            this.chNFe = value;
        }

        
        public XMLGregorianCalendar getDhRecbto() {
            return dhRecbto;
        }

        
        public void setDhRecbto(XMLGregorianCalendar value) {
            this.dhRecbto = value;
        }

        
        public String getNProt() {
            return nProt;
        }

        
        public void setNProt(String value) {
            this.nProt = value;
        }

        
        public byte[] getDigVal() {
            return digVal;
        }

        
        public void setDigVal(byte[] value) {
            this.digVal = ((byte[]) value);
        }

        
        public String getCStat() {
            return cStat;
        }

        
        public void setCStat(String value) {
            this.cStat = value;
        }

        
        public String getXMotivo() {
            return xMotivo;
        }

        
        public void setXMotivo(String value) {
            this.xMotivo = value;
        }

        
        public String getId() {
            return id;
        }

        
        public void setId(String value) {
            this.id = value;
        }

    }

}
