//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 06:02:18 PM BRST 
//

package br.com.caelum.stella.nfe.modelo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import net.vidageek.fluid.annotations.FluidName;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRetConsReciNFe", propOrder = { "tpAmb", "verAplic", "nRec", "cStat", "xMotivo", "cuf", "protNFe" })
@FluidName("retornoDoPedidoDeConsultaDoRecidoDoLoteDeNFE")
public class TRetConsReciNFe {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("tipoDeAmbiente")
    protected String tpAmb;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("versaoDaAplicativo")
    protected String verAplic;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("numeroDoReciboConsultado")
    protected String nRec;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("codigoDeStatus")
    protected String cStat;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("descricaoDoStatus")
    protected String xMotivo;

    @XmlElement(name = "cUF", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("codigoDaUF")
    protected String cuf;

    @FluidName("protocoloDoResultadoDeProcessamento")
    protected List<TProtNFe> protNFe;

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @FluidName("versaoNFE")
    protected String versao;

    public String getTpAmb() {
        return tpAmb;
    }

    public void setTpAmb(final String value) {
        tpAmb = value;
    }

    public String getVerAplic() {
        return verAplic;
    }

    public void setVerAplic(final String value) {
        verAplic = value;
    }

    public String getNRec() {
        return nRec;
    }

    public void setNRec(final String value) {
        nRec = value;
    }

    public String getCStat() {
        return cStat;
    }

    public void setCStat(final String value) {
        cStat = value;
    }

    public String getXMotivo() {
        return xMotivo;
    }

    public void setXMotivo(final String value) {
        xMotivo = value;
    }

    public String getCUF() {
        return cuf;
    }

    public void setCUF(final String value) {
        cuf = value;
    }

    public List<TProtNFe> getProtNFe() {
        if (protNFe == null) {
            protNFe = new ArrayList<TProtNFe>();
        }
        return protNFe;
    }

    public String getVersao() {
        return versao;
    }

    public void setVersao(final String value) {
        versao = value;
    }

    public void setProtNFe(final List<TProtNFe> protNFe) {
        this.protNFe = protNFe;
    }

}
