//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 06:02:18 PM BRST 
//

package br.com.caelum.stella.nfe.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVeiculo", propOrder = { "placa", "uf", "rntc" })
public class TVeiculo {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String placa;

    @XmlElement(name = "UF", required = true)
    protected TUf uf;

    @XmlElement(name = "RNTC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rntc;

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String value) {
        this.placa = value;
    }

    public TUf getUF() {
        return uf;
    }

    public void setUF(TUf value) {
        this.uf = value;
    }

    public String getRNTC() {
        return rntc;
    }

    public void setRNTC(String value) {
        this.rntc = value;
    }

}
