
package br.com.caelum.stella.nfe.ws.sp.recepcao;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Serviço destinado à recepção de mensagens de lote de NF-e.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NfeRecepcao2", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2", wsdlLocation = "file:/Users/mariodoamaralgoncalves/caelum/caelum-stella/stella-nfe/wsdls/homol/sp/NfeRecepcao2.wsdl")
public class NfeRecepcao2
    extends Service
{

    private final static URL NFERECEPCAO2_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.caelum.stella.nfe.ws.sp.recepcao.NfeRecepcao2 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.caelum.stella.nfe.ws.sp.recepcao.NfeRecepcao2 .class.getResource(".");
            url = new URL(baseUrl, "file:/Users/mariodoamaralgoncalves/caelum/caelum-stella/stella-nfe/wsdls/homol/sp/NfeRecepcao2.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/mariodoamaralgoncalves/caelum/caelum-stella/stella-nfe/wsdls/homol/sp/NfeRecepcao2.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NFERECEPCAO2_WSDL_LOCATION = url;
    }

    public NfeRecepcao2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeRecepcao2() {
        super(NFERECEPCAO2_WSDL_LOCATION, new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2", "NfeRecepcao2"));
    }

    /**
     * 
     * @return
     *     returns NfeRecepcao2Soap12
     */
    @WebEndpoint(name = "NfeRecepcao2Soap12")
    public NfeRecepcao2Soap12 getNfeRecepcao2Soap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2", "NfeRecepcao2Soap12"), NfeRecepcao2Soap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeRecepcao2Soap12
     */
    @WebEndpoint(name = "NfeRecepcao2Soap12")
    public NfeRecepcao2Soap12 getNfeRecepcao2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2", "NfeRecepcao2Soap12"), NfeRecepcao2Soap12.class, features);
    }

}
